#!/usr/bin/env python

import time

print("Pulling from Google Sheets...")
curl https://sheetsu.com/apis/v1.0/8f11913607ba -o src/data/challenges-current.json
time.sleep(1)
print("Successfully pulled")
